### ISSUE TITLE
[全般] 患者台帳の "予後調査" 項目の表示位置について

### ISSUE THREAD

**Issue by akihikoueda** [jesgo-toitu/jesgo-schema#32]
婦人科腫瘍登録対象症例を 「はい」にした場合に表示される、
予後調査 と 腫瘍登録番号の項目 が 下に入るため、タブが下に移動していまいます。
予後調査の段組を廃し、以下の添付画像のように、右に
「腫瘍登録番号」「予後調査 3年」「予後調査 5年」
という形ででるとスッキリするように思いますが、
このような形での制御は可能でしょうか？
なお、3年、5年は必須項目として JSOGマークを付してください。
また、横の ？ の部分は 現行の 予後調査の横についている？と
注意書きの表示は同じで結構です。

<img width="590" alt="image" src="https://github.com/jesgo-toitu/jesgo-schema/assets/49895496/353f0998-b7ab-4428-b6bd-12838090384d">

**Comment by piyotaicho** [comment]
2カラム表示は実装しておりませんのでこの形での表示方法はできません、申し訳ありません。
（手術入力の項目の扱いは若干異なります）

**Comment by piyotaicho** [comment]
現状で可能な感じだとこのようになりますが、これはどうでしょう？一行だけ短くなります。
![image](https://github.com/jesgo-toitu/jesgo-schema/assets/57445173/7a6351f0-252a-49b2-8c36-c215c56823d6)

**Comment by akihikoueda** [comment]
ご検討ありがとうございます。
承知いたしました。
予後調査については、ご提案の通りでお願いできますと幸いです。

**Comment by saso-hokuto** [comment]
[開発メモ]
- 予後調査を横並びに
- 「予後調査 3年」「予後調査 5年」にJSOG必須を追加
