### ISSUE TITLE
病期診断で「遠隔転移の部位」をブランク選択しないとエラーが表示される。

### ISSUE THREAD

**Issue by akihikoueda** [jesgo-toitu/jesgo-schema#33]
現象確認：
2023年以前の日付での症例登録、「患者台帳 卵巣がん」
添付のように、遠隔転移の部位を「ブランク」状態で選択しないと保存時に

【 患者台帳 卵巣がん > 病期診断 】
　　[ 遠隔転移の部位 ] 1件以上入力してください。

とのエラーが表示されます。
ご確認をお願いいたします。
(※ 2024年の登録項目でも同様のエラーを認めました)

![スクリーンショット 2023-11-22 5 23 24](https://github.com/jesgo-toitu/jesgo-schema/assets/49895496/14546203-3758-497a-a13c-7709db93cacb)

**Comment by hsc-morita** [comment]
[開発メモ]
遠隔転移の部位は"minItems": 1 の設定を削除し、0件でもエラーにならないようにする
