### ISSUE TITLE
Performance statusのタイトル

### ISSUE THREAD

**Issue by piyotaicho** [jesgo-toitu/jesgo-schema#5]
いま、データベースを飛ばしたので復旧していたら
"title": "Performance status"
のスペース入りで作成してしまっていた事実が発覚しました。
さて困った。
```
update jesgo_document_schema set title = 'PerformanceStatus', subtitle = '', document_schema = '...' where title = 'Performance' and subtitle = 'Status';
```
をアップデートのリリースで仕込んでいただいて、標準配布スキーマは修正して対処しましょうか。

**Comment by kosaka-hokuto** [comment]
他にもjesgo:tagなどの対応でアップロードするスキーマが存在するため、こちらについてもスキーマのアップロードで対応してもよろしいでしょうか？
バージョンを変えたくない等、SQLで対応しなければいけない理由があればお教えください。
